name: CALM VScode Extension

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "plugins/calm-vscode/**"
      - "shared/**"
  push:
    branches:
      - "main"
    paths:
      - "plugins/calm-vscode/**"
      - "shared/**"

defaults:
  run:
    working-directory: ./plugins/calm-vscode

jobs:
  calm-vscode-tests:
    name: Run unit tests and lint
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/javascript-node:0-18
    steps:
      # Check out the repository
      - uses: actions/checkout@v4
      # Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: v20

      # Ensure shared is built.
      - name: Install & Build Shared Module
        working-directory: ./shared
        run: |
          npm install
          npm run build

      - name: Install & Build Shared Module
        run: |
          npm ci
          npm run test
          npm run lint
          npm run build