name: Release and Publish CLI

permissions:
    contents: write
    issues: write
    pull-requests: write

on:
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            # Checkout the code with full history for semantic-release
            - name: Checkout code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
              with:
                  fetch-depth: 0

            # Set up Node.js
            - name: Setup Node.js
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
              with:
                  node-version: v22
                  registry-url: 'https://registry.npmjs.org'

            # Install the workspace
            - name: Install workspace
              run: npm ci

            # Build the entire workspace
            - name: Build workspace
              run: npm run build

            # Run semantic-release for CLI
            - name: Release CLI
              run: npm run semantic-release --workspace cli
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
